container:
  port: 80
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 1
      memory: 1000Mi
  env: {}

service:
  port: 8090

ingress:
  enabled: true
  domain: ai45.shlab.org.cn
  path: /
  https: true
  secretName: shlab.org.cn-https
