ls:
  src:
    .dir: kebab-case # applies to the current directory and all their subdirectories
    .js: kebab-case
    .ts: kebab-case
    .json: kebab-case
    .vue: kebab-case
    .tsx: kebab-case
    .d.ts: kebab-case
    .module.less: kebab-case
    .less: kebab-case

ignore:
  - .git
  - node_modules
